<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>active_sonar</name>
  <version>0.0.0</version>
  <description>Active sonar sensor for LOTUSim</description>
  <maintainer email="newsther@yahoo.com">esther</maintainer>
  <license>EPL-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>lotusim_sensor_base</depend>
  <depend>lotusim_sensor_msgs</depend>
  <depend>lotusim_common</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
