ARG ROS2_VERSION
ARG GAZEBO_VERSION
ARG HTTP_PROXY
ARG HTTPS_PROXY

FROM ngfe/ros_gz_base:${ROS2_VERSION}-${GAZEBO_VERSION}

COPY df-ca.crt /usr/local/share/ca-certificates/df-ca.crt

# Set environment variables
ENV LOTUSIM_WS=/home/lotusim_ws \
    LOTUSIM_PATH=/home/lotusim_ws/src/lotusim \
    LOTUSIM_MODELS_PATH=/home/lotusim_ws/src/lotusim/assets/models \
    PATH=/home/lotusim_ws/src/lotusim/physics:/home/lotusim_ws/src/lotusim/launch:$PATH \
    LD_LIBRARY_PATH=/home/lotusim_ws/src/lotusim/physics:$LD_LIBRARY_PATH \
    FASTDDS_BUILTIN_TRANSPORTS=UDPv4 

ENV http_proxy=$HTTP_PROXY \
    https_proxy=$HTTPS_PROXY

# Set the working directory
WORKDIR /home/lotusim_ws

# Copy local files to the container
COPY . ./src/lotusim 

# Use bash shell
SHELL ["/bin/bash", "-c"]

RUN echo "HTTP_PROXY=$http_proxy" && \
    echo "HTTPS_PROXY=$https_proxy" && \
    lotusim build_lotus && \
    rm -rf ./src/lotusim/systems ./src/lotusim/gui

ENTRYPOINT ["/bin/bash"]

