sonar.projectKey=naval-group_LOTUSim
sonar.organization=naval-group

sonar.sources=systems,interfaces
sonar.sourceEncoding=UTF-8

# C++ analysis requires a compilation database for accurate symbol resolution
sonar.cfamily.compile-commands=build/compile_commands.json

sonar.exclusions=**/test/**,**/build/**,**/install/**,**/log/**
