FROM ubuntu:22.04

# Set environment variables
ENV LOTUSIM_WS=/home/lotusim_ws \
    LOTUSIM_PATH=/home/lotusim_ws/src/LOTUSim \
    LOTUSIM_MODELS_PATH=/home/lotusim_ws/src/LOTUSim/assets/models \
    PATH=/home/lotusim_ws/src/LOTUSim/physics:/home/lotusim_ws/src/LOTUSim/launch:$PATH \
    LD_LIBRARY_PATH=/home/lotusim_ws/src/LOTUSim/physics:$LD_LIBRARY_PATH \
    FASTDDS_BUILTIN_TRANSPORTS=UDPv4 

# Set the working directory
WORKDIR /home/lotusim_ws

# Copy local files to the container
COPY launch/install_dep.sh ./install_dep.sh

# Use bash shell
SHELL ["/bin/bash", "-c"]

RUN chmod +x ./install_dep.sh && \
    ./install_dep.sh

ENTRYPOINT ["/bin/bash"]

