FROM ros_gz_base:latest

# Set environment variables
ENV LOTUSIM_WS=/home/lotusim_ws \
    LOTUSIM_PATH=/home/lotusim_ws/src/lotusim \
    LOTUSIM_MODELS_PATH=/home/lotusim_ws/src/lotusim/assets/models \
    PATH=/home/lotusim_ws/src/lotusim/physics:/home/lotusim_ws/src/lotusim/launch:$PATH \
    LD_LIBRARY_PATH=/home/lotusim_ws/src/lotusim/physics:$LD_LIBRARY_PATH \
    FASTDDS_BUILTIN_TRANSPORTS=UDPv4 

# Set the working directory
WORKDIR /home/lotusim_ws

# Copy local files to the container
COPY ./lotusim ./src/lotusim 

COPY ./lotusim_backend ./src/lotusim_backend 

# Use bash shell
SHELL ["/bin/bash", "-c"]

RUN rm -rf ./src/lotusim/gui && \
    lotusim build && \
    chmod +x ./src/lotusim/launch/entrypoint.sh

ENTRYPOINT ["/home/lotusim_ws/src/lotusim/launch/entrypoint.sh"]
CMD ["/bin/bash"]