#!/bin/bash
# Color definitions
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Default configurations
DEFAULT_WORLD="lotusim.world"

ASSETS_PATH="${LOTUSIM_PATH}/assets"
MODEL_PATH="${ASSETS_PATH}/models"
WORLD_PATH="${ASSETS_PATH}/worlds"

# Flags for simulation options
DEBUG="-v0"
GUI="-s"


###########
# Functions
###########
print_help() {
    echo -e "${GREEN}Usage:${NC} lotusim [OPTIONS] <command> [world_name]"
    echo -e "${GREEN}Options:${NC}"
    echo -e "  --ws-path PATH          Path to the lotusim workspace (default: $LOTUSIM_WS)"
    echo -e "  --assets-path PATH      Path to the assets directory (default: $ASSETS_PATH)"
    echo -e "  --debug                 Enable debug mode"
    echo -e "  --gui                   Run gz sim GUI"
    echo -e "  --help                  Display this help message"
    echo ""
    echo -e "${GREEN}Commands:${NC}"
    echo -e "  install                 Install the dependencies"
    echo -e "  clean                   Clean the project"
    echo -e "  build                   Build the project"
    echo -e "  build_lotus             Build the lotus only"
    echo -e "  clean_build             Clean and build the project"
    echo -e "  doc                     Generate project documentation"
    echo -e "  run                     Run the simulation [optional: world_name]"
    echo ""
    echo -e "${GREEN}Example:${NC}"
    echo -e "  lotusim --ws-path /new/path/to/ws --debug --gui run my_world_name"
}

install_lotus_dep() {
    echo "Installing dependencies..."
    if [ "$EUID" -ne 0 ]; then
        sudo -E "$LOTUSIM_PATH/launch/install_dep.sh"
    else
        "$LOTUSIM_PATH/launch/install_dep.sh"
    fi
}

install_ui() {
    echo -e "
********************************************************************************************
******************************    ${GREEN}Installing Lotusim$ UI{NC}    **********************************
********************************************************************************************
    "
    echo -e "\n🔄 Sourcing ROS workspace setup..."
    source "${LOTUSIM_WS}/install/setup.bash"

    echo -e "\n⬇️  Installing NVM..."
    curl -s -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash >/dev/null

    echo -e "\n📦 Loading NVM into current shell..."
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

    echo -e "\n📦 Installing Node.js v18 with NVM..."
    nvm install 18 >/dev/null
    nvm use 18 >/dev/null

    echo -e "
********************************************************************************************
*******************************    ${GREEN}Installing UI backend{NC}   *********************************
********************************************************************************************
    "

    BACKEND_DIR="${LOTUSIM_WS}/src/lotusim_backend"
    if [ -d "$BACKEND_DIR" ]; then
        echo -e "\n📦 Installing backend dependencies..."
        npm install --silent --prefix "$BACKEND_DIR" >/dev/null 2>&1

        echo -e "\n⚙️  Generating ROS messages for backend..."
        npx --prefix "$BACKEND_DIR" generate-ros-messages >/dev/null 2>&1
    else
        echo -e "\n⚠️  Backend directory not found: $BACKEND_DIR — skipping backend installation."
    fi

    echo -e "
********************************************************************************************
*******************************    ${GREEN}Installing UI frontend{NC}  *********************************
********************************************************************************************
    "

    FRONTEND_DIR="${LOTUSIM_WS}/src/lotusim_ui"
    if [ -d "$FRONTEND_DIR" ]; then
        echo -e "\n📦 Installing frontend dependencies..."
        npm install --silent --prefix "$FRONTEND_DIR" >/dev/null 2>&1
    else
        echo -e "\n⚠️  Frontend directory not found: $FRONTEND_DIR — skipping frontend installation."
    fi

    echo -e "\n✅ UI installation complete."
}


build_lotus() {
    echo -e "
********************************************************************************************
*******************************    ${GREEN}Installing Lotusim${NC}    ***********************************
********************************************************************************************
    "
    source "/opt/ros/humble/setup.bash"
    cd ${LOTUSIM_WS}
    if [ "$DEBUG" == "-v4" ]; then
        echo "Debug mode enabled: Printing out debug logs. Enabling LOTUSIM_TIDY"
        colcon build --cmake-args -DLOTUSIM_TIDY=ON -DDEBUG=ON --symlink-install --merge-install || {
            echo -e "${RED}Error:${NC} Build failed."
            exit 1
        }
    else
        colcon build --merge-install || {
            echo -e "${RED}Error:${NC} Build failed."
            exit 1
        }
    fi
}

validate_setup() {
    if [ ! -f "/opt/ros/humble/setup.bash" ]; then
        echo -e "${RED}Error:${NC} ROS2 Humble is not installed or the setup.bash is not found at /opt/ros/humble/setup.bash."
        exit 1
    fi
    if [ ! -d "${LOTUSIM_WS}" ]; then
        echo -e "${RED}Error:${NC} The lotusim workspace does not exist at $LOTUSIM_WS."
        exit 1
    fi
    if [ ! -d "${LOTUSIM_PATH}" ]; then
        echo -e "${RED}Error:${NC} The lotusim repo does not exist at $LOTUSIM_PATH."
        exit 1
    fi
}

#######
# Main
#######
export GZ_VERSION=harmonic

# Check if no command is provided
if [ $# -eq 0 ]; then
    echo -e "${RED}Error:${NC} No command provided."
    print_help
    exit 1
fi

# Parse arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
    --ws-path)
        LOTUSIM_WS="$2"
        shift
        ;;
    --assets-path)
        ASSETS_PATH="$2"
        shift
        ;;
    --debug)
        DEBUG="-v4"
        ;;
    --gui)
        GUI=""
        ;;
    --help)
        print_help
        exit 0
        ;;
    -*)
        echo -e "${RED}Invalid option:${NC} $1"
        print_help
        exit 1
        ;;
    *)
        COMMAND=$1
        shift
        break
        ;;
    esac
    shift
done

# Execute the command
case $COMMAND in
install)
    install_lotus_dep
    echo "Building the project..."
    validate_setup
    build_lotus
    install_ui
    ;;
install_lotus)
    install_lotus_dep
    validate_setup
    build_lotus
    ;;
clean)
    rm -rf "${LOTUSIM_WS}/log" "${LOTUSIM_WS}/install" "${LOTUSIM_WS}/build"
    ;;
build)
    clear
    validate_setup
    build_lotus
    install_ui
    ;;
build_lotus)
    clear
    validate_setup
    build_lotus
    ;;
clean_build)
    clear
    echo "Cleaning and building the project..."
    rm -rf "${LOTUSIM_WS}/log" "${LOTUSIM_WS}/install" "${LOTUSIM_WS}/build"
    build_lotus
    ;;
doc)
    cd "${LOTUSIM_PATH}/docs" || {
        echo -e "${RED}Error:${NC} Failed to change directory to docs."
        exit 1
    }
    doxygen Doxyfile || {
        echo -e "${RED}Error:${NC} Documentation generation failed."
        exit 1
    }
    echo "Docs generated at ${LOTUSIM_PATH}/docs"
    ;;
run)
    clear
    validate_setup

    source "/opt/ros/humble/setup.bash"
    source "${LOTUSIM_WS}/install/setup.bash"

    export GZ_SIM_SYSTEM_PLUGIN_PATH="${LOTUSIM_WS}/install/lib"
    export GZ_GUI_PLUGIN_PATH="${LOTUSIM_WS}/install/lib"
    export GZ_SIM_RESOURCE_PATH="${MODEL_PATH}"

    echo -e "${GREEN}GZ_SIM_SYSTEM_PLUGIN_PATH${NC}: $GZ_SIM_SYSTEM_PLUGIN_PATH"
    echo -e "${GREEN}GZ_SIM_RESOURCE_PATH${NC}: $GZ_SIM_RESOURCE_PATH"

    WORLD=${1:-$DEFAULT_WORLD}

    echo -e "${GREEN}Running the simulation world ${NC}: ${WORLD_PATH}/${WORLD}"
    gz sim ${DEBUG} ${GUI} -r "${WORLD_PATH}/${WORLD}"
    ;;

    # TODO: Common bridge is not done yet. Change all GZ transport to ROS2 transport and have common launch script to bridge world gz msg
    # run-w-bridge)
    #     echo "Running the simulation."
    #     source "/opt/ros/humble/setup.bash"
    #     source "${LOTUSIM_WS}/install/setup.bash"

    #     export GZ_SIM_SYSTEM_PLUGIN_PATH="${LOTUSIM_WS}/install/lib"
    #     export GZ_SIM_RESOURCE_PATH="${ASSETS_PATH}"

    #     echo -e "GZ_SIM_SYSTEM_PLUGIN_PATH: ${GREEN}$GZ_SIM_SYSTEM_PLUGIN_PATH${NC}"
    #     echo -e "GZ_SIM_RESOURCE_PATH: ${GREEN}$GZ_SIM_RESOURCE_PATH${NC}"

    #     ros2 launch assets common_ros_bridge.launch.py &
    #     pidBridge=$!

    #     WORLD=${1:-$DEFAULT_WORLD}
    #     gz sim ${DEBUG} ${GUI} -r "${WORLD_PATH}/${WORLD}"

    #     killBridge() {
    #         echo "Killing Lotus."
    #         kill $pidBridge
    #         wait $pidBridge
    #         echo "Bridge killed."
    #         exit 0
    #     }
    #     trap killBridge SIGINT
    #     wait $pidBridge
    #     ;;

    # TODO: A dream for now. Someone who actually bother to read this, please help me to do it. Or you can ignore it totally.
    # mas)
    # ;;

*)
    echo -e "${RED}Invalid command: $COMMAND${NC}"
    print_help
    exit 1
    ;;
esac
